### ISSUE TITLE
What is Espresso?  Link Broken.

### ISSUE THREAD

**Issue by pa1shetty** [amitshekhariitbhu/android-interview-questions#117]
What is Espresso?  Link is Broken.
Working link https://developer.android.com/training/testing/espresso

**Comment by Satya-Prakashan** [comment]
Here is the Working Link 👍
[https://developer.android.com/training/testing/espresso/basics](https://developer.android.com/training/testing/espresso/basics)

**Comment by amitshekhariitbhu** [comment]
Updated
