### ISSUE TITLE
[Critical Issue] Mistake in README file which can mislead a beginner

### ISSUE THREAD

**Issue by Subhadiptech** [amitshekhariitbhu/android-interview-questions#134]
While reading I found that there was a question under OOPS section that 

_Can you list 8 primitive types in java?_

Present ans: 
byte
short
int
long
float
double
char
String
boolean

Expected ans:

byte
short
int
long
float
double
char
boolean

`String` is not a primitive data type of Java.

This point may mislead a beginner.

**Comment by amitshekhariitbhu** [comment]
Updated
